### ISSUE TITLE
[Setup] Create a node server using Typescript

### ISSUE THREAD

**Issue by sksmsdkdl23** [ElkPine/HUBIoT#1]
Create a node server with typescript and TsLint applied.

**Comment by MykalMachon** [comment]
Do you need a hand getting an express server going?
I haven't used typescript in a while, but I can try and get a PR in with a basic node server infrastructure setup with controllers and all that. 

Let me know!

**Comment by sksmsdkdl23** [comment]
@MykalMachon I'm gonna be using this project to learn and get my hands dirty so I'll probably do it myself. However, you can talk to @Markusmoo and try working on other projects we have planned to do.

Thanks 👍
